### PR TITLE
Update SwiftEventBus.swift

### PR DESCRIPTION
**Pull request by jaimeagudo**
Overload `post` to accept `sender:Any?` it seems perfectly valid as per apple-reference-documentation://hsOxvRvq26

### CODE REVIEW

**Comment by nunogoncalves** [comment]
I agree with you, and think we can make it better. 

`open class func post(_ name: String, sender: Any? = nil)` would allow us to remove the overloaded method. :)

**Comment by jaimeagudo** [comment]
I am glad you are open to contributions, let me do it, I'd love to contribute further when I get a better understanding on the NSNotifications (and find time). I have a lean for primitive types as Clojurian at ❤️ , data is just data :)

**Comment by nunogoncalves** [comment]
Did you have a change to test it with both examples?

**Comment by nunogoncalves** [comment]
REmove your overloaded method. It's not needed anymore. :)

**Comment by nunogoncalves** [comment]
Doing this: `func post(_ name: String, sender: Any? = nil)` you allow both 
`post("Event")` and `post("Event", sender: object)` to be called

**Comment by jaimeagudo** [comment]
I already did it 5 mins ago :)

**Comment by nunogoncalves** [comment]
Oh sorry. Don't want to cause you trouble, but since you're working on this, in order to keep consistency, can you do the same with the other methods? 👍

**Comment by jaimeagudo** [comment]
Ok, the initial change compiles and works, I agree on the refactor but I'd downcast all the `sender.AnyObject?` to `sender:Any?` which is what the underlaying Apple API is requiring anyway, are you happy with it?

**Comment by nunogoncalves** [comment]
Yes. :) Go for it. :)

**Comment by jaimeagudo** [comment]
Please review the changes with this link to ignore white space @nunogoncalves  [https://github.com/cesarferreira/SwiftEventBus/pull/23/commits/05ac44912160207058d2193421e4d0be40368158?w=1](url)

**Comment by nunogoncalves** [comment]
404. :)

**Comment by jaimeagudo** [comment]
oh! You were too quick, I fixed it immediately :)

**Comment by jaimeagudo** [comment]
The resultant API https://github.com/jaimeagudo/SwiftEventBus/blob/05ac44912160207058d2193421e4d0be40368158/SwiftEventBus/SwiftEventBus.swift looks simpler

**Comment by cesarferreira** [comment]
Ok, I'll release it, thanks @jaimeagudo

**Comment by cesarferreira** [comment]
it's on `2.2.0`

**Pull request merged**
