### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by migore**
@heckfer and I added Carthage support to SwiftEventBus, we just had to share the scheme. We also had to create a new tag, to make it work you need to create a new tag manually in your project repository as well.

Cheers

### CODE REVIEW

**Comment by cesarferreira** [comment]
@migore Thanks for the PR.
So you want me to create a "1.1" tag?

**Comment by migore** [comment]
Yes. By doing that carthage will understand things automatically.

**Comment by cesarferreira** [comment]
Done ;)
I've called it "1.1.0" for semantic versioning reasons http://semver.org/

thanks ;)
let me know if everything is ok

**Comment by migore** [comment]
Thanks, work like a charm!

**Comment by cesarferreira** [comment]
cool, thanks for the pull request

**Pull request merged**
